### ISSUE TITLE
Crash of Latte Dock when Weather Widgets is not fully loaded.

### ISSUE THREAD

**Issue by Petross404** [kotelnik/plasma-applet-weather-widget#50]
Hello and congratulations for this cool applet. I am a user of a new dock (Latte Dock) and I noticed that when Latte is fresh-started and Weather Widget is clicked, Latte crashes.

Not that as soon I start my dock I check the weather. I was just fooling around and thought that you may want to know this.

[latte-dock-20170312-145841.kcrash.txt](https://github.com/kotelnik/plasma-applet-weather-widget/files/837917/latte-dock-20170312-145841.kcrash.txt)

You can take a look [here](https://github.com/psifidotos/Latte-Dock/issues/253) to see what is all about.

Have a nice day :)

EDIT: Of course weather widget is "pinned" on the dock, not on the desktop or something.

**Comment by kotelnik** [comment]
I cannot confirm this. I'm really trying to open the widget as soon as latte is started but I cannot make it crash. But in crash log, I can see XmlListModel so I have a clue.

Do you by any chance use OWM location? Because I definitely have crashes when using this provider (regardless of Latte or Plasma panel). It is likely caused by some memory corruption in Qt's XmlListModel but I am still unable to create a small application to reliably replicate the crash in order to make a bug report.

**Comment by kotelnik** [comment]
I may have fix the crashing (in OWM provider handler code). Please reopen this if still occurs.
